# backend/app/core/constants.py
# Shared constants used by scrapers and API

SEASON_MAP = {
    # Aug–May
    "ENG-PL": "2025-2026", "ENG-CH": "2025-2026",
    "ESP-LL": "2025-2026", "ESP-LL2": "2025-2026",
    "FRA-L1": "2025-2026", "FRA-L2": "2025-2026",
    "GER-BUN": "2025-2026", "GER-B2": "2025-2026",
    "ITA-SA": "2025-2026", "ITA-SB": "2025-2026",
    "NED-ERE": "2025-2026",
    "TUR-SL": "2025-2026",
    "SAU-SPL": "2025-2026",
    "DEN-SL": "2025-2026",
    "BEL-PL": "2025-2026",
    "MEX-LMX": "2025-2026",
    "POL-EK": "2025-2026",
    "AUT-BL": "2025-2026",
    "SUI-SL": "2025-2026",
    "CHI-LP": "2025-2026",
    "PER-L1": "2025-2026",
    "POR-LP": "2025-2026",
    # Calendar year
    "BRA-SA": "2026", "BRA-SB": "2026",
    "MLS": "2026",
    "NOR-EL": "2026", "SWE-AL": "2026",
    "CHN-CSL": "2026", "JPN-J1": "2026",
    "COL-PA": "2026",
}

LEAGUE_MAP = {
    "ENG-PL":  "https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures",
    "ENG-CH":  "https://fbref.com/en/comps/10/schedule/Championship-Scores-and-Fixtures",
    "ESP-LL":  "https://fbref.com/en/comps/12/schedule/La-Liga-Scores-and-Fixtures",
    "FRA-L1":  "https://fbref.com/en/comps/13/schedule/Ligue-1-Scores-and-Fixtures",
    "GER-BUN": "https://fbref.com/en/comps/20/schedule/Bundesliga-Scores-and-Fixtures",
    "ITA-SA":  "https://fbref.com/en/comps/11/schedule/Serie-A-Scores-and-Fixtures",
    "NED-ERE": "https://fbref.com/en/comps/23/schedule/Eredivisie-Scores-and-Fixtures",
    "TUR-SL":  "https://fbref.com/en/comps/26/schedule/Super-Lig-Scores-and-Fixtures",
    "BRA-SA":  "https://fbref.com/en/comps/24/schedule/Serie-A-Scores-and-Fixtures",
    "MLS":     "https://fbref.com/en/comps/22/schedule/Major-League-Soccer-Scores-and-Fixtures",
    "SAU-SPL": "https://fbref.com/en/comps/70/schedule/Saudi-Pro-League-Scores-and-Fixtures",
    "DEN-SL":  "https://fbref.com/en/comps/50/schedule/Danish-Superliga-Scores-and-Fixtures",
    "ESP-LL2": "https://fbref.com/en/comps/17/schedule/Segunda-Division-Scores-and-Fixtures",
    "BEL-PL":  "https://fbref.com/en/comps/37/schedule/Belgian-Pro-League-Scores-and-Fixtures",
    "NOR-EL":  "https://fbref.com/en/comps/28/schedule/Eliteserien-Scores-and-Fixtures",
    "SWE-AL":  "https://fbref.com/en/comps/29/schedule/Allsvenskan-Scores-and-Fixtures",
    "MEX-LMX": "https://fbref.com/en/comps/31/schedule/Liga-MX-Scores-and-Fixtures",
    "CHN-CSL": "https://fbref.com/en/comps/62/schedule/Chinese-Super-League-Scores-and-Fixtures",
    "JPN-J1":  "https://fbref.com/en/comps/25/schedule/J1-League-Scores-and-Fixtures",
    "COL-PA":  "https://fbref.com/en/comps/41/schedule/Primera-A-Scores-and-Fixtures",
    "BRA-SB":  "https://fbref.com/en/comps/38/schedule/Serie-B-Scores-and-Fixtures",
    "ITA-SB":  "https://fbref.com/en/comps/18/schedule/Serie-B-Scores-and-Fixtures",
    "FRA-L2":  "https://fbref.com/en/comps/60/schedule/Ligue-2-Scores-and-Fixtures",
    "GER-B2":  "https://fbref.com/en/comps/33/schedule/2-Bundesliga-Scores-and-Fixtures",
    "POL-EK":  "https://fbref.com/en/comps/36/schedule/Ekstraklasa-Scores-and-Fixtures",
    "AUT-BL":  "https://fbref.com/en/comps/56/schedule/Austrian-Football-Bundesliga-Scores-and-Fixtures",
    "SUI-SL":  "https://fbref.com/en/comps/57/schedule/Swiss-Super-League-Scores-and-Fixtures",
    "CHI-LP":  "https://fbref.com/en/comps/35/schedule/Primera-Division-Scores-and-Fixtures",
    "PER-L1":  "https://fbref.com/en/comps/44/schedule/Liga-1-Scores-and-Fixtures",
    "POR-LP":  "https://fbref.com/en/comps/32/schedule/Primeira-Liga-Scores-and-Fixtures",
    "UCL":     "https://fbref.com/en/comps/8/schedule/Champions-League-Scores-and-Fixtures",
    "UEL":     "https://fbref.com/en/comps/19/schedule/Europa-League-Scores-and-Fixtures",
    "UECL":    "https://fbref.com/en/comps/882/schedule/Conference-League-Scores-and-Fixtures",
}
